from api.config import router as config_router
from api.chat.router import router as chat_router
from api.sessions import router as sessions_router
from api.work_dirs import router as work_dirs_router
from api.scheduled_tasks import router as scheduled_tasks_router
from api.platforms import router as platforms_router
from api.system import router as system_router
from api.terminal import router as terminal_router
from api.skills import router as skills_router
from api.plugins import router as plugins_router
from api.subagents import router as subagents_router
from api.upload import router as upload_router
from api.debug import router as debug_router
from api.path_permissions import router as path_permissions_router
from api.git_api import router as git_router
from api.files_api import router as files_router
from api.chat_ws import router as chat_ws_router
from api.memory import router as memory_router
from api.pets_api import router as pets_router
from api.network_api import router as network_router
from api.main_agent_api import router as main_agent_router
from api.plugins_builtin import router as plugins_builtin_router
