# -*- mode: python ; coding: utf-8 -*-

from PyInstaller.utils.hooks import collect_submodules

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('api', 'api'),
        ('db', 'db'),
        ('models', 'models'),
        ('services', 'services'),
        ('utils', 'utils'),
        ('plugins', 'plugins'),
        ('tools', 'tools'),
        ('prompt', 'prompt'),
        ('memory', 'memory'),
        ('aries_mcp', 'aries_mcp'),
    ],
    hiddenimports=[
        'uvicorn',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.loops.auto',
        'httpx',
        'websockets',
        'sqlalchemy',
        'openai',
        'python_multipart',
        'aiofiles',
        'qrcode',
        'PIL',
        'dotenv',
        'lark_oapi',
        'mcp',
        'pypdf',
        'pydantic',
        'pydantic_settings',
        'passlib',
        'bcrypt',
        'cryptography',
        'pyflakes',
        'psutil',
        'send2trash',
    ],
    hookspath=[],
    hooksconfig={},
    excludes=[
        'pandas',
        'openpyxl',
        'moviepy',
        'matplotlib',
        'scipy',
        'sklearn',
        'tensorflow',
        'torch',
        'seaborn',
        'plotly',
        'bokeh',
        'dash',
        'flask',
        'django',
        'notebook',
        'ipython',
        'jupyter',
        'streamlit',
        'boto3',
        'botocore',
        's3transfer',
        'paramiko',
        'docker',
        'kubernetes',
        'tkinter',
        'unittest',
        'pytest',
        'PyQt5',
        'PyQt6',
        'PySide2',
        'PySide6',
        'wx',
        'win32com',
        'win32api',
        'win32gui',
        'win32con',
        'pythoncom',
        'pywintypes',
    ],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='aries',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)