#!/usr/bin/env node
// index.js — Computer Use MCP Server
//
// Exposes OpenAI Codex computer-use (sky Window2 API) as MCP tools so that ANY
// MCP-capable agent with vision can drive the Windows GUI: list apps/windows,
// read accessibility trees, click by element index OR screenshot coordinates, type text,
// press keys, scroll, set values, drag, launch/activate windows — and return
// screenshots as image content blocks the agent's vision model can actually see.
//
// The heavy lifting is done by OpenAI's codex-computer-use.exe, bundled inside
// the parent computer_use skill at scripts/codex-computer-use.exe. This server
// is a thin, dependency-light Node.js wrapper around that executable's JSON-RPC protocol.

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { getClient } from "./sky_client.js";

// ── Coercion helpers ────────────────────────────────────────────
// Some MCP clients (notably wrappers that auto-serialize JSON args) forward
// numeric fields as JSON strings. To keep the server robust we accept either
// type at the schema layer and coerce to number at the call site. The lower
// level (SkyClient → codex-computer-use.exe) still receives real numbers.
function num(v) {
  if (v === undefined || v === null || v === "") return undefined;
  if (typeof v === "number") return Number.isFinite(v) ? v : undefined;
  if (typeof v === "string") {
    const n = Number(v);
    return Number.isFinite(n) ? n : undefined;
  }
  return undefined;
}
function int(v) {
  const n = num(v);
  return n === undefined ? undefined : Math.trunc(n);
}
// zod schema that accepts both number and string-number, validated as finite.
const Num = z
  .union([z.number(), z.string()])
  .transform((v, ctx) => {
    const n = num(v);
    if (n === undefined) {
      ctx.addIssue({ code: z.ZodIssueCode.custom, message: "expected a number" });
      return z.NEVER;
    }
    return n;
  });
const Int = Num.transform((n) => Math.trunc(n));

const server = new McpServer({
  name: "computer-use-mcp-server",
  version: "1.0.0",
});

// ── Window object schema ──────────────────────────────────────────────
// A window is identified by { app, id }. app is an app identifier string
// (e.g. "process:WeChat.exe" or "Microsoft.AutoGenerated.{...}"); id is the
// opaque window handle number returned by list_windows/list_apps.
const WindowSchema = z
  .object({
    app: z
      .string()
      .describe(
        "App identifier from list_apps/list_windows, e.g. \"process:WeChat.exe\" or \"Microsoft.AutoGenerated.{...}\"",
      ),
    id: Num.describe(
      "Opaque window handle id (number or numeric string) returned by discovery tools",
    ),
    title: z.string().optional().describe("Optional window title for reference"),
  })
  .strict()
  .describe("Target window object returned by list_apps / list_windows");

function textBlock(text) {
  return { type: "text", text };
}

// Wrap a get_window_state result's screenshots into image content blocks.
// `state.screenshots[i].url` comes back from codex-computer-use.exe as a
// `data:<mime>;base64,<payload>` URL. The MCP ImageContent schema requires
// `data` to be the raw base64 payload (no prefix) and `mimeType` to be the
// media type. We split the data URL here so MCP clients receive a valid
// ImageContent block.
const DATA_URL_RE = /^data:([^;,]+)?(;base64)?,(.*)$/s;

function parseDataUrl(url) {
  if (typeof url !== "string") return null;
  const m = DATA_URL_RE.exec(url);
  if (!m) return null;
  return {
    mimeType: m[1] || "image/png",
    isBase64: m[2] === ";base64",
    payload: m[3] || "",
  };
}

function screenshotBlocks(state) {
  const blocks = [];
  const shots = (state && state.screenshots) || [];
  for (const s of shots) {
    if (!s || typeof s.url !== "string") continue;
    const parsed = parseDataUrl(s.url);
    if (parsed) {
      blocks.push({
        type: "image",
        data: parsed.payload,
        mimeType: parsed.mimeType,
      });
    } else {
      // Fall back to treating the value as a plain base64 payload.
      blocks.push({ type: "image", data: s.url, mimeType: "image/png" });
    }
  }
  return blocks;
}

// Build a compact text description of window state.
function describeState(state) {
  if (!state) return "(no state returned)";
  const lines = [];
  const win = state.window || {};
  lines.push(
    `Window: app=${win.app ?? "?"} id=${win.id ?? "?"} title=${win.title ?? ""}`,
  );
  if (state.accessibility && state.accessibility.tree) {
    lines.push("Accessibility tree:");
    lines.push(state.accessibility.tree);
    if (state.accessibility.focused_element) {
      lines.push(`Focused: ${state.accessibility.focused_element}`);
    }
    if (state.accessibility.selected_text) {
      lines.push(`Selected text: ${state.accessibility.selected_text}`);
    }
  } else {
    lines.push(
      "(no accessibility tree — this app exposes no UI Automation controls)",
    );
  }
  const shots = state.screenshots || [];
  if (shots.length) {
    lines.push(
      `Screenshots: ${shots.length} image(s) returned as image blocks (use them to locate coordinates).`,
    );
    for (const s of shots) {
      if (s.width && s.height) {
        lines.push(`  - screenshot ${s.id}: ${s.width}x${s.height}`);
      }
    }
  }
  return lines.join("\n");
}

// ── Tool: list_apps ────────────────────────────────────────────────
server.registerTool(
  "list_apps",
  {
    title: "List installed apps",
    description:
      "List installed applications discoverable by computer-use, including whether each is running and its currently open targetable windows.\n\n" +
      "Use this first to discover what apps exist and obtain Window objects. Each returned app has an id (app identifier) and a windows array; each window is a {app, id, title} object you pass to other * tools.\n\n" +
      'Only returns apps that expose discoverable windows. For apps not listed, pass an explicit .exe path/identifier to launch_app (e.g. "process:C:\\\\Path\\\\App.exe").',
    inputSchema: {
      runningOnly: z
        .boolean()
        .default(false)
        .describe("If true, only return apps that are currently running"),
    },
    outputSchema: {
      apps: z.array(z.any()),
    },
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true,
    },
  },
  async ({ runningOnly }) => {
    const client = getClient();
    let apps = await client.listApps();
    if (runningOnly) apps = apps.filter((a) => a.isRunning);
    return {
      content: [textBlock(JSON.stringify(apps, null, 2))],
      structuredContent: { apps },
    };
  },
);

// ── Tool: list_windows ────────────────────────────────────────────
server.registerTool(
  "list_windows",
  {
    title: "List open windows",
    description:
      "List all currently open windows that can be targeted by computer-use.\n\n" +
      "Returns an array of Window objects {app, id, title}. Pick the window matching the task and reuse its object for subsequent * calls (click/type/etc). Do NOT construct window objects yourself — always take them from this tool's (or list_apps') output.",
    inputSchema: {},
    outputSchema: { windows: z.array(z.any()) },
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: true,
    },
  },
  async () => {
    const client = getClient();
    const windows = await client.listWindows();
    return {
      content: [textBlock(JSON.stringify(windows, null, 2))],
      structuredContent: { windows },
    };
  },
);

// Shared helper: capture window state and format it as MCP content blocks.
async function captureWindowState(window, { includeScreenshot, includeText }) {
  const client = getClient();
  const state = await client.getWindowState(window, {
    includeScreenshot,
    includeText,
  });
  const blocks = screenshotBlocks(state);
  const text = describeState(state);
  return {
    content: [textBlock(text), ...blocks],
    structuredContent: {
      description: text,
      screenshotCount: blocks.length,
    },
  };
}

// ── Tool: get_window_state ───────────────────────────────────────
server.registerTool(
  "get_window_state",
  {
    title: "Get window state (screenshot + accessibility tree)",
    description:
      "Capture the current state of a target window: a screenshot (returned as an image content block the vision model can see) AND/OR an accessibility tree (element index to label mapping).\n\n" +
      "This is the CORE tool. Call it to (a) see the UI via screenshot, and (b) get clickable element indices.\n\n" +
      "include_screenshot=true (default): returns an image block. Use it to locate UI coordinates when there is no accessibility tree.\n" +
      "include_text=true: returns a text tree with element indices (e.g. \"6 编辑 ...\"). Prefer this for native Win32/UWP apps — then click by element_index instead of coordinates.\n\n" +
      "After any UI change, call this again to re-read state (indices may shift after menu opens).",
    inputSchema: {
      window: WindowSchema,
      includeScreenshot: z
        .boolean()
        .default(true)
        .describe("Return an image screenshot of the window"),
      includeText: z
        .boolean()
        .default(true)
        .describe("Return the accessibility tree with element indices"),
    },
    outputSchema: {
      description: z.string(),
      screenshotCount: z.number(),
    },
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window, includeScreenshot, includeText }) =>
    captureWindowState(window, { includeScreenshot, includeText }),
);

// ── Tool: take_screenshot ─────────────────────────────────────────
server.registerTool(
  "take_screenshot",
  {
    title: "Take a screenshot of a window",
    description:
      "Capture a screenshot of the target window and return it as an image content block. " +
      "Use this when you only need the visual state and not the accessibility tree.\n\n" +
      "For coordinate-based clicks (click with x/y), call this first to obtain the image, " +
      "then read pixel coordinates from it. Screenshot ids are currently informational; " +
      "coordinate clicks accept the most recent screenshot implicitly.",
    inputSchema: {
      window: WindowSchema,
    },
    outputSchema: {
      description: z.string(),
      screenshotCount: z.number(),
    },
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window }) => captureWindowState(window, { includeScreenshot: true, includeText: false }),
);

// ── Tool: get_accessibility_tree ──────────────────────────────────
server.registerTool(
  "get_accessibility_tree",
  {
    title: "Get accessibility tree of a window",
    description:
      "Capture the accessibility tree (UI Automation controls with element indices) of the target window. " +
      "Returns a text tree where each line looks like \"6 编辑 ...\".\n\n" +
      "Use this before click(elementIndex) / set_value / perform_secondary_action so you " +
      "can refer to UI elements by their stable index. After any UI change, call this again " +
      "because indices may shift.",
    inputSchema: {
      window: WindowSchema,
    },
    outputSchema: {
      description: z.string(),
      screenshotCount: z.number(),
    },
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window }) => captureWindowState(window, { includeScreenshot: false, includeText: true }),
);

// ── Tool: click ───────────────────────────────────────────────────
server.registerTool(
  "click",
  {
    title: "Click in a window",
    description:
      "Click inside a target window. Two modes:\n\n" +
      "1) Element-index click (PREFERED when the last get_window_state returned an accessibility tree): pass element_index from that tree. Precise and robust to layout shifts.\n" +
      "2) Coordinate click (for apps with NO accessibility tree, e.g. Electron/Chromium like WeChat/VS Code): first call get_window_state(include_screenshot=true) to get an image block, read the (x,y) pixel position from the screenshot, then pass x,y AND the screenshotId from that state. Coordinates are in the screenshot's pixel space (origin = window top-left).\n\n" +
      "clickCount>1 for double-click. mouseButton: left|right|middle.",
    inputSchema: {
      window: WindowSchema,
      elementIndex: Int.optional().describe(
        "Element index from the latest accessibility tree (preferred when available)",
      ),
      x: Num.optional().describe(
        "X pixel coordinate in the window screenshot (for coordinate clicks)",
      ),
      y: Num.optional().describe(
        "Y pixel coordinate in the window screenshot (for coordinate clicks)",
      ),
      screenshotId: z
        .string()
        .optional()
        .describe(
          "Screenshot id from the get_window_state call that produced the coordinates",
        ),
      clickCount: Int.refine((n) => n >= 1 && n <= 3, {
        message: "clickCount must be 1..3",
      })
        .optional()
        .describe("Number of clicks (2 = double click)"),
      mouseButton: z
        .enum(["left", "right", "middle", "l", "r", "m"])
        .optional()
        .describe("Mouse button to click"),
    },
    outputSchema: { ok: z.boolean() },
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window, elementIndex, x, y, screenshotId, clickCount, mouseButton }) => {
    const client = getClient();
    await client.click(window, {
      elementIndex,
      x,
      y,
      screenshotId,
      clickCount,
      mouseButton,
    });
    return { content: [textBlock("Clicked.")], structuredContent: { ok: true } };
  },
);

// ── Tool: type_text ──────────────────────────────────────────────
server.registerTool(
  "type_text",
  {
    title: "Type text into focused element",
    description:
      "Type text into the currently focused element of the target window (supports Chinese and other Unicode). Prefer this over clipboard paste for most inputs.\n\n" +
      "If nothing is focused, click the target input first (click with element_index or x,y), then call this. For reliable replacement of an editable value, use set_value instead.",
    inputSchema: {
      window: WindowSchema,
      text: z.string().describe("Text to type (Unicode/Chinese supported)"),
    },
    outputSchema: { ok: z.boolean() },
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window, text }) => {
    const client = getClient();
    await client.typeText(window, text);
    return {
      content: [textBlock(`Typed: ${text}`)],
      structuredContent: { ok: true },
    };
  },
);

// ── Tool: press_key ──────────────────────────────────────────────
server.registerTool(
  "press_key",
  {
    title: "Press a key or key chord",
    description:
      'Press a key or "+" separated key chord using X Window keysym-style names.\n\n' +
      'Examples: "Return" (Enter), "Escape", "Tab", "space", "F5", "Control_L+a" (Ctrl+A), "Control_L+Shift_L+period", "Alt_L+F4", "Up"/"Down"/"Left"/"Right".\n\n' +
      "Modifiers: Control_L, Shift_L, Alt_L. Common aliases (Ctrl/Alt/Shift/period/Numpad_0) are accepted.",
    inputSchema: {
      window: WindowSchema,
      key: z
        .string()
        .describe('Key or chord, e.g. "Return", "Control_L+a", "Escape"'),
    },
    outputSchema: { ok: z.boolean() },
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window, key }) => {
    const client = getClient();
    await client.pressKey(window, key);
    return {
      content: [textBlock(`Pressed: ${key}`)],
      structuredContent: { ok: true },
    };
  },
);

// ── Tool: scroll ────────────────────────────────────────────────
server.registerTool(
  "scroll",
  {
    title: "Scroll in a window",
    description:
      "Scroll from a coordinate in the target window. Requires a prior get_window_state(include_screenshot=true) screenshotId.\n\n" +
      "scrollX: negative=left, positive=right. scrollY: negative=up, positive=down. Magnitude is scroll amount (pixels-ish); use larger values to scroll further.",
    inputSchema: {
      window: WindowSchema,
      x: Num.describe(
        "X pixel coordinate (in the window screenshot) to scroll from",
      ),
      y: Num.describe(
        "Y pixel coordinate (in the window screenshot) to scroll from",
      ),
      scrollX: Num.describe(
        "Horizontal scroll delta (negative=left, positive=right)",
      ),
      scrollY: Num.describe(
        "Vertical scroll delta (negative=up, positive=down)",
      ),
      screenshotId: z
        .string()
        .optional()
        .describe("Screenshot id from the get_window_state call"),
    },
    outputSchema: { ok: z.boolean() },
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window, x, y, scrollX, scrollY, screenshotId }) => {
    const client = getClient();
    await client.scroll(window, { x, y, scrollX, scrollY, screenshotId });
    return { content: [textBlock("Scrolled.")], structuredContent: { ok: true } };
  },
);

// ── Tool: set_value ─────────────────────────────────────────────
server.registerTool(
  "set_value",
  {
    title: "Set editable element value",
    description:
      "Directly replace the value of an indexed editable element (text box, etc.) from the latest accessibility tree. More reliable than type_text for replacing existing content (it sets the value outright).\n\n" +
      "element_index comes from the latest get_window_state(include_text=true) tree.",
    inputSchema: {
      window: WindowSchema,
      elementIndex: Int.describe(
        "Element index of the editable element from the accessibility tree",
      ),
      value: z
        .string()
        .describe("Replacement value (Unicode/Chinese supported)"),
    },
    outputSchema: { ok: z.boolean() },
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window, elementIndex, value }) => {
    const client = getClient();
    await client.setValue(window, elementIndex, value);
    return {
      content: [textBlock(`Set value: ${value}`)],
      structuredContent: { ok: true },
    };
  },
);

// ── Tool: drag ────────────────────────────────────────────────
server.registerTool(
  "drag",
  {
    title: "Drag from one coordinate to another",
    description:
      "Drag from (fromX,fromY) to (toX,toY) inside the target window. Requires a prior get_window_state(include_screenshot=true) screenshotId for coordinate resolution.\n\n" +
      "Coordinates are in the window-screenshot pixel space (origin = window top-left).",
    inputSchema: {
      window: WindowSchema,
      fromX: Num.describe("Start X (window-screenshot pixel space)"),
      fromY: Num.describe("Start Y (window-screenshot pixel space)"),
      toX: Num.describe("End X (window-screenshot pixel space)"),
      toY: Num.describe("End Y (window-screenshot pixel space)"),
      screenshotId: z
        .string()
        .optional()
        .describe("Screenshot id from the get_window_state call"),
    },
    outputSchema: { ok: z.boolean() },
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window, fromX, fromY, toX, toY, screenshotId }) => {
    const client = getClient();
    await client.drag(window, { fromX, fromY, toX, toY, screenshotId });
    return { content: [textBlock("Dragged.")], structuredContent: { ok: true } };
  },
);

// ── Tool: launch_app ───────────────────────────────────────────
server.registerTool(
  "launch_app",
  {
    title: "Launch an application",
    description:
      'Launch an application by its id (from list_apps) or by an explicit .exe path/identifier (e.g. "process:C:\\\\Windows\\\\notepad.exe" or "notepad").\n\n' +
      'After launching, call list_windows (or list_apps) again to obtain the new window\'s Window object, then operate on it. Some apps take a few seconds to open a window.',
    inputSchema: {
      app: z
        .string()
        .describe(
          'App id from list_apps, or ".exe" path/identifier, e.g. "process:C:\\\\Windows\\\\notepad.exe"',
        ),
    },
    outputSchema: { ok: z.boolean() },
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: true,
    },
  },
  async ({ app }) => {
    const client = getClient();
    await client.launchApp(app);
    return {
      content: [textBlock(`Launched: ${app}`)],
      structuredContent: { ok: true },
    };
  },
);

// ── Tool: activate_window ──────────────────────────────────────
server.registerTool(
  "activate_window",
  {
    title: "Bring window to foreground",
    description:
      "Bring a target window to the foreground (optional escape hatch). Note: click/type/press_key already auto-activate their target window before acting, so you usually do NOT need this. Use it only when you need a window visible before a screenshot.",
    inputSchema: { window: WindowSchema },
    outputSchema: { ok: z.boolean() },
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window }) => {
    const client = getClient();
    await client.activateWindow(window);
    return {
      content: [textBlock("Activated window.")],
      structuredContent: { ok: true },
    };
  },
);

// ── Tool: get_window ───────────────────────────────────────────
server.registerTool(
  "get_window",
  {
    title: "Rehydrate a window by id",
    description:
      'Re-fetch a currently-open window object by its id (e.g. after a stale handle / "window not found" error). Returns a fresh Window object you can reuse.\n\n' +
      "If the window is gone, launch it again via launch_app and re-discover via list_windows.",
    inputSchema: {
      app: z
        .string()
        .optional()
        .describe("Optional app identifier to carry forward"),
      id: Num.describe("Window id (number or numeric string) from a previous discovery"),
    },
    outputSchema: { window: z.any() },
    annotations: {
      readOnlyHint: true,
      destructiveHint: false,
      idempotentHint: true,
      openWorldHint: false,
    },
  },
  async ({ app, id }) => {
    const client = getClient();
    const window = await client.getWindow({ app, id });
    return {
      content: [textBlock(JSON.stringify(window))],
      structuredContent: { window },
    };
  },
);

// ── Tool: perform_secondary_action ────────────────────────────
server.registerTool(
  "perform_secondary_action",
  {
    title: "Invoke accessibility secondary action",
    description:
      'Invoke a secondary accessibility action on an indexed element from the latest get_window_state tree.\n\n' +
      'action examples (case-insensitive): "Raise", "Scroll Up", "Scroll Down", "Scroll Left", "Scroll Right", "Expand", "Collapse". These come from the accessibility tree\'s reported secondary actions.',
    inputSchema: {
      window: WindowSchema,
      action: z
        .string()
        .describe('Secondary action label, e.g. "Raise", "Expand", "Scroll Down"'),
      elementIndex: Int.describe(
        "Element index from the accessibility tree",
      ),
    },
    outputSchema: { ok: z.boolean() },
    annotations: {
      readOnlyHint: false,
      destructiveHint: false,
      idempotentHint: false,
      openWorldHint: false,
    },
  },
  async ({ window, action, elementIndex }) => {
    const client = getClient();
    await client.performSecondaryAction(window, action, elementIndex);
    return {
      content: [textBlock(`Performed: ${action}`)],
      structuredContent: { ok: true },
    };
  },
);

// ── Graceful shutdown ──────────────────────────────────────────
function shutdown() {
  try {
    getClient().close();
  } catch {
    /* ignore */
  }
  process.exit(0);
}
process.on("SIGINT", shutdown);
process.on("SIGTERM", shutdown);
process.on("exit", () => {
  try {
    getClient().close();
  } catch {
    /* ignore */
  }
});

async function main() {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  process.stderr.write("computer-use-mcp-server running on stdio\n");
}

main().catch((err) => {
  process.stderr.write(`Fatal: ${err?.stack || err}\n`);
  process.exit(1);
});
