"""
Prompt 模板集中管理模块
所有 AI 交互用的 prompt 模板都放在这个目录下
"""

from .coding_agent_prompts import (
    CODE_STYLE_RULES,
    CODING_BEHAVIOR_RULES,
    COMMUNICATION_RULES,
    COMPLETION_HONESTY_RULES,
    DOING_TASKS_RULES,
    PLANNING_RULES,
    PROMPT_INJECTION_AWARENESS,
    RISK_AWARE_ACTIONS_RULES,
    TOOL_DESCRIPTION_GUIDELINES,
    TOOL_DISCIPLINE_RULES,
)

__all__ = [
    "CODE_STYLE_RULES",
    "CODING_BEHAVIOR_RULES",
    "COMMUNICATION_RULES",
    "COMPLETION_HONESTY_RULES",
    "DOING_TASKS_RULES",
    "PLANNING_RULES",
    "PROMPT_INJECTION_AWARENESS",
    "RISK_AWARE_ACTIONS_RULES",
    "TOOL_DESCRIPTION_GUIDELINES",
    "TOOL_DISCIPLINE_RULES",
]
