"""
Prompt 模板集中管理模块
所有 AI 交互用的 prompt 模板都放在这个目录下
"""

from .coding_agent_prompts import (
    CODE_STYLE_RULES,
    CODING_BEHAVIOR_RULES,
    COMMUNICATION_RULES,
    COMPLETION_HONESTY_RULES,
    DOING_TASKS_RULES,
    PLANNING_RULES,
    PROMPT_INJECTION_AWARENESS,
    RISK_AWARE_ACTIONS_RULES,
    TOOL_DESCRIPTION_GUIDELINES,
    TOOL_DISCIPLINE_RULES,
)

from .edit_code_prompts import (
    EDIT_CODE_CORE_RULES,
    EDIT_TOOL_SELECTION_RULES,
    EDIT_FILE_SEARCH_REPLACE_GUIDE,
    MULTI_REPLACE_STRING_GUIDE,
    APPLY_PATCH_GUIDE,
    EDIT_REMINDER_RULES,
    FIX_INTENT_PROMPT,
    EXPLAIN_INTENT_PROMPT,
    SEARCH_INTENT_PROMPT,
    CREATE_INTENT_PROMPT,
    INTENT_CLASSIFICATION_PROMPT,
    build_edit_code_prompt,
    build_intent_specific_prompt,
    build_optimized_edit_prompt,
    PromptSection,
    PromptBuilder,
    # 意图识别
    INTENT_EDIT,
    INTENT_FIX,
    INTENT_EXPLAIN,
    INTENT_SEARCH,
    INTENT_REVIEW,
    INTENT_CREATE,
    INTENT_AGENT,
    classify_intent,
    get_tools_for_intent,
    filter_tools_for_intent,
    get_prompt_for_intent,
)

from .agent_prompts import (
    ASK_SYSTEM_PROMPT,
    EXPLORE_SYSTEM_PROMPT,
    PLAN_SYSTEM_PROMPT,
    AGENT_MODES,
    get_agent_mode,
    filter_tools_for_agent,
)

__all__ = [
    "CODE_STYLE_RULES",
    "CODING_BEHAVIOR_RULES",
    "COMMUNICATION_RULES",
    "COMPLETION_HONESTY_RULES",
    "DOING_TASKS_RULES",
    "PLANNING_RULES",
    "PROMPT_INJECTION_AWARENESS",
    "RISK_AWARE_ACTIONS_RULES",
    "TOOL_DESCRIPTION_GUIDELINES",
    "TOOL_DISCIPLINE_RULES",
    # 编辑代码专用 prompt
    "EDIT_CODE_CORE_RULES",
    "EDIT_TOOL_SELECTION_RULES",
    "EDIT_FILE_SEARCH_REPLACE_GUIDE",
    "MULTI_REPLACE_STRING_GUIDE",
    "APPLY_PATCH_GUIDE",
    "EDIT_REMINDER_RULES",
    "FIX_INTENT_PROMPT",
    "EXPLAIN_INTENT_PROMPT",
    "SEARCH_INTENT_PROMPT",
    "CREATE_INTENT_PROMPT",
    "INTENT_CLASSIFICATION_PROMPT",
    "build_edit_code_prompt",
    "build_intent_specific_prompt",
    "build_optimized_edit_prompt",
    "PromptSection",
    "PromptBuilder",
    # 意图识别
    "INTENT_EDIT",
    "INTENT_FIX",
    "INTENT_EXPLAIN",
    "INTENT_SEARCH",
    "INTENT_REVIEW",
    "INTENT_CREATE",
    "INTENT_AGENT",
    "classify_intent",
    "get_tools_for_intent",
    "filter_tools_for_intent",
    "get_prompt_for_intent",
    # 固定 Agent 模式
    "ASK_SYSTEM_PROMPT",
    "EXPLORE_SYSTEM_PROMPT",
    "PLAN_SYSTEM_PROMPT",
    "AGENT_MODES",
    "get_agent_mode",
    "filter_tools_for_agent",
]
